### 외부 csv파일을 가지고 와서 판다스 데이터 프레임 형식으로 바꾸기

In [ ]:
import pandas as pd		  # 데이터 프레임을 만들 판다스

In [9]:
file_path = '../Data/big_data_set1_f.csv'

In [13]:
pd.read_csv(file_path, encoding='cp949')

,ENCODED_MCT,MCT_BSE_AR,MCT_NM,MCT_BRD_NUM,MCT_SIGUNGU_NM,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D
0,16184E93D9,서울 성동구 마장동,성우**,NaN,서울 성동구,축산물,마장동,20130320,NaN
1,4D039EA8B7,서울 성동구 마장동,대보**,NaN,서울 성동구,축산물,마장동,20131122,NaN
2,0074C4990A,서울 성동구 마장동,대용**,NaN,서울 성동구,축산물,마장동,20140512,NaN
3,68308F2746,서울 성동구 마장동,통일**,NaN,서울 성동구,축산물,마장동,20151124,NaN
4,4117EDDE9C,서울 성동구 마장동,한울**,NaN,서울 성동구,축산물,마장동,20151211,NaN
...,...,...,...,...,...,...,...,...,...
4180,7FCF23E6F3,서울특별시 성동구 마장로 137,아이**********,NaN,서울 성동구,아이스크림/빙수,NaN,20230821,NaN
4181,9743B78531,서울 성동구 독서당로 223,어반**,NaN,서울 성동구,양식,NaN,20130305,NaN
4182,C2261977A8,서울특별시 성동구 마장로35길 76,한성**,NaN,서울 성동구,축산물,NaN,20230517,NaN
4183,F1C69918DF,서울 성동구 왕십리로 410,국수**,한식-국수/만두3,서울 성동구,한식-국수/만두,NaN,20211007,NaN
4184,58B8C943BF,서울특별시 성동구 매봉길 50,아이******,NaN,서울 성동구,아이스크림/빙수,NaN,20230303,NaN